"""Academic report generator.

Produces paper-ready analysis reports from a collection of
interpreted analysis results. Supports multiple output formats:
Markdown (for preview), HTML, and structured JSON (for .docx/.qmd export).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class ReportSection:
    """A single section of the report (one analysis)."""

    heading: str  # e.g., "Descriptive Statistics"
    subheading: str = ""  # e.g., "Income Distribution"
    interpretation: str = ""  # Natural language interpretation
    tables: list[dict] = field(default_factory=list)
    # Each table: {"title": str, "columns": [...], "rows": [[...]]}
    figures: list[str] = field(default_factory=list)  # Figure descriptions
    safety_notes: list[str] = field(default_factory=list)


@dataclass
class Report:
    """A complete academic report."""

    title: str = "Quantrix Analysis Report"
    dataset_name: str = ""
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    format: str = "apa"  # "apa", "chinese"

    # Metadata
    n_rows: int = 0
    n_columns: int = 0
    source_format: str = ""

    # Content
    sections: list[ReportSection] = field(default_factory=list)

    # Quality notes
    limitations: list[str] = field(default_factory=list)


class ReportGenerator:
    """Generates academic reports from analysis results.

    Usage:
        gen = ReportGenerator()
        report = gen.create_report("My Study", sections=[...])
        markdown = gen.render_markdown(report)
    """

    def create_report(
        self,
        title: str,
        dataset_info: dict | None = None,
        sections: list[ReportSection] | None = None,
        fmt: str = "apa",
    ) -> Report:
        """Create a Report from sections."""
        ds = dataset_info or {}
        return Report(
            title=title,
            dataset_name=ds.get("name", ""),
            format=fmt,
            n_rows=ds.get("n_rows", 0),
            n_columns=ds.get("n_columns", 0),
            source_format=ds.get("source_format", ""),
            sections=sections or [],
        )

    def render_markdown(self, report: Report) -> str:
        """Render a Report to Markdown (APA 7th format)."""
        lines: list[str] = []

        # Title
        lines.append(f"# {report.title}")
        lines.append("")

        # Method section (dataset info)
        if report.dataset_name:
            lines.append("## Method")
            lines.append("")
            lines.append(f"Data were obtained from the **{report.dataset_name}** dataset")
            lines.append(
                f"({report.source_format.upper() if report.source_format else 'CSV'} format), "
            )
            lines.append(f"containing N = {report.n_rows} observations ")
            lines.append(f"across {report.n_columns} variables.")
            lines.append("")

        # Results
        if report.sections:
            lines.append("## Results")
            lines.append("")

        for _i, section in enumerate(report.sections):
            if section.heading:
                lines.append(f"### {section.heading}")
                lines.append("")
            if section.subheading:
                lines.append(f"**{section.subheading}**")
                lines.append("")

            # Interpretation text
            if section.interpretation:
                lines.append(section.interpretation.strip())
                lines.append("")

            # Tables
            for table in section.tables:
                lines.extend(self._render_table_markdown(table))
                lines.append("")

            # Safety notes
            for note in section.safety_notes:
                lines.append(f"> ⚠️ {note}")
                lines.append("")

        # Limitations
        if report.limitations:
            lines.append("## Limitations")
            lines.append("")
            for lim in report.limitations:
                lines.append(f"- {lim}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Report generated by Quantrix v0.1.0 on {report.generated_at[:10]}*")

        return "\n".join(lines)

    def render_html(self, report: Report) -> str:
        """Render a Report to HTML."""
        md = self.render_markdown(report)
        # Simple Markdown-to-HTML conversion (no external dependency)
        html_lines = ["<div class='quantrix-report'>"]

        for line in md.split("\n"):
            if line.startswith("# "):
                html_lines.append(f"<h1>{line[2:]}</h1>")
            elif line.startswith("## "):
                html_lines.append(f"<h2>{line[3:]}</h2>")
            elif line.startswith("### "):
                html_lines.append(f"<h3>{line[4:]}</h3>")
            elif line.startswith("**") and line.endswith("**"):
                html_lines.append(f"<p><strong>{line[2:-2]}</strong></p>")
            elif line.startswith("> "):
                html_lines.append(f"<blockquote>{line[2:]}</blockquote>")
            elif line.startswith("- "):
                html_lines.append(f"<li>{line[2:]}</li>")
            elif line.startswith("|"):
                # Table row — handled by table renderer
                html_lines.append(f"<span class='table-row'>{line}</span>")
            elif line == "":
                html_lines.append("<br/>")
            elif line.startswith("---"):
                html_lines.append("<hr/>")
            else:
                html_lines.append(f"<p>{line}</p>")

        html_lines.append("</div>")
        return "\n".join(html_lines)

    def _render_table_markdown(self, table: dict) -> list[str]:
        """Render a table dict as Markdown."""
        lines: list[str] = []

        title = table.get("title", "")
        if title:
            lines.append(f"**{title}**")
            lines.append("")

        columns: list[str] = table.get("columns", [])
        rows: list[list] = table.get("rows", [])

        if not columns:
            # Simple key-value table
            for key, val in table.items():
                if key not in ("title", "columns", "rows", "notes"):
                    lines.append(f"- **{key}**: {val}")
            return lines

        # Header
        header = "| " + " | ".join(str(c) for c in columns) + " |"
        sep = "|" + "|".join("---" for _ in columns) + "|"
        lines.append(header)
        lines.append(sep)

        # Rows
        for row in rows:
            cells = [str(c) if c is not None else "—" for c in row]
            lines.append("| " + " | ".join(cells) + " |")

        notes = table.get("notes", "")
        if notes:
            lines.append(f"*Note.* {notes}")

        return lines


# ── Factory helpers ─────────────────────────────────────────────────────


def section_from_interpretation(
    heading: str,
    interpretation: str,
    tables: list[dict] | None = None,
    safety_notes: list[str] | None = None,
    subheading: str = "",
) -> ReportSection:
    """Create a ReportSection from an interpretation result."""
    return ReportSection(
        heading=heading,
        subheading=subheading,
        interpretation=interpretation,
        tables=tables or [],
        safety_notes=safety_notes or [],
    )
