"""R code exporter — generates reproducible R scripts from DAG."""

from __future__ import annotations

from quantrix.dag.graph import AnalysisDAG, NodeKind


def export_r(dag: AnalysisDAG, dataset_name: str = "data") -> str:
    """Export the DAG as a reproducible R script."""
    lines: list[str] = [
        "#!/usr/bin/env Rscript",
        "# Reproducible analysis script generated by Quantrix",
        "",
        "library(haven)      # for read_sav",
        "library(readr)      # for read_csv",
        "",
        "# ── Load data ──",
        "# Replace with your actual data loading",
        f'# df <- read_csv("{dataset_name}.csv")',
        f'# df <- read_sav("{dataset_name}.sav")',
        "",
        'cat(sprintf("Loaded %d rows × %d columns\\n", nrow(df), ncol(df)))',
        "",
    ]

    nodes = dag.topological_order()
    for node in nodes:
        if node.kind == NodeKind.IMPORT:
            lines.append(f"# Import: {node.description}")
            lines.append("")
        elif node.kind == NodeKind.ANALYSIS:
            lines.append(f"# ── {node.label} ──")
            lines.extend(_export_analysis_r(node))
            lines.append("")

    return "\n".join(lines)


def _export_analysis_r(node) -> list[str]:
    method = node.method
    params = node.parameters
    dv = params.get("dv", "outcome")
    iv = params.get("iv", "predictor")

    if method == "independent_ttest":
        return [
            f"# t-test: {dv} by {iv}",
            f"result <- t.test(df${dv} ~ df${iv})",
            "print(result)",
        ]
    elif method == "oneway_anova":
        return [
            f"# ANOVA: {dv} by {iv}",
            f"result <- aov({dv} ~ factor({iv}), data = df)",
            "print(summary(result))",
        ]
    elif method == "pearson_correlation":
        return [
            f"# Correlation: {dv} × {iv}",
            f"result <- cor.test(df${dv}, df${iv}, method = 'pearson')",
            "print(result)",
        ]
    elif method == "chi_square":
        return [
            f"# Chi-square: {dv} × {iv}",
            f"result <- chisq.test(table(df${iv}, df${dv}))",
            "print(result)",
        ]
    elif method == "linear_regression":
        return [
            f"# Linear regression: {dv} ~ {iv}",
            f"model <- lm({dv} ~ {iv}, data = df)",
            "print(summary(model))",
        ]
    else:
        return [
            f"# {method} analysis",
            f"# Parameters: {params}",
        ]
