"""SPSS Syntax exporter — generates SPSS Syntax from DAG."""

from __future__ import annotations

from quantrix.dag.graph import AnalysisDAG, NodeKind


def export_syntax(dag: AnalysisDAG, dataset_name: str = "data") -> str:
    """Export the DAG as SPSS Syntax."""
    lines: list[str] = [
        "* Reproducible SPSS Syntax generated by Quantrix.",
        f"* Dataset: {dataset_name}",
        "",
        "GET FILE='data.sav'.",
        "",
    ]

    nodes = dag.topological_order()
    for node in nodes:
        if node.kind == NodeKind.IMPORT:
            lines.append(f"* Import: {node.description}.")
            lines.append("")
        elif node.kind == NodeKind.ANALYSIS:
            lines.append(f"* ── {node.label} ──.")
            lines.extend(_export_analysis_sps(node))
            lines.append("")

    return "\n".join(lines)


def _export_analysis_sps(node) -> list[str]:
    method = node.method
    params = node.parameters
    dv = params.get("dv", "outcome")
    iv = params.get("iv", "predictor")

    if method == "independent_ttest":
        return [
            f"T-TEST GROUPS={iv}(1 2)",
            f"  /VARIABLES={dv}.",
        ]
    elif method == "oneway_anova":
        return [
            f"ONEWAY {dv} BY {iv}",
            "  /STATISTICS DESCRIPTIVES.",
        ]
    elif method == "chi_square":
        return [
            "CROSSTABS",
            f"  /TABLES={iv} BY {dv}",
            "  /STATISTICS=CHISQ.",
        ]
    elif method == "pearson_correlation":
        return [
            "CORRELATIONS",
            f"  /VARIABLES={dv} {iv}",
            "  /PRINT=TWOTAIL NOSIG.",
        ]
    elif method == "linear_regression":
        return [
            "REGRESSION",
            f"  /DEPENDENT={dv}",
            f"  /METHOD=ENTER {iv}.",
        ]
    elif method in ("descriptive_statistics", "descriptives"):
        return [
            f"DESCRIPTIVES VARIABLES={dv}",
            "  /STATISTICS=MEAN STDDEV MIN MAX.",
        ]
    elif method == "frequency_analysis":
        return [
            f"FREQUENCIES VARIABLES={dv}",
            "  /ORDER=ANALYSIS.",
        ]
    else:
        return [
            f"* {method}.",
            f"* Parameters: {params}.",
        ]
