"""Python code exporter for reproducibility."""

from __future__ import annotations

from quantrix.dag.graph import AnalysisDAG, NodeKind


def _get_dv_iv(params: dict[str, object]) -> tuple[str, str]:
    dv = str(params.get("dv", "outcome"))
    ivs = params.get("ivs")
    iv = str(ivs[0]) if isinstance(ivs, list) and ivs else str(params.get("iv", "predictor"))
    return dv, iv


def export_python(dag: AnalysisDAG, dataset_name: str = "data") -> str:
    lines = [
        '"""Reproducible analysis script generated by Quantrix."""',
        "",
        "import polars as pl",
        "from scipy import stats",
        "import statsmodels.api as sm",
        "",
        f"# Load data: {dataset_name}",
        f"# df = pl.read_csv('{dataset_name}.csv')",
        "",
    ]

    for node in dag.topological_order():
        if node.kind == NodeKind.IMPORT:
            lines.append(f"# Import: {node.description}")
        elif node.kind == NodeKind.ANALYSIS:
            lines.append(f"# {node.label}")
            params = dict(node.parameters)
            dv, iv = _get_dv_iv(params)
            m = node.method

            if m == "independent_ttest":
                lines.append(f"groups_raw = df['{iv}'].drop_nulls().unique().sort().to_list()")
                lines.append(f"mask = df['{dv}'].is_not_null() & df['{iv}'].is_not_null()")
                lines.append(f"g1 = df.filter(mask & (pl.col('{iv}') == groups_raw[0]))['{dv}'].to_numpy()")
                lines.append(f"g2 = df.filter(mask & (pl.col('{iv}') == groups_raw[1]))['{dv}'].to_numpy()")
                lines.append("t, p = stats.ttest_ind(g1, g2)")
                lines.append("print(f't={t:.3f}, p={p:.4f}')")
            elif m == "pearson_correlation":
                lines.append(
                    f"r, p = stats.pearsonr(df['{dv}'].drop_nulls(), df['{iv}'].drop_nulls())"
                )
                lines.append("print(f'r={r:.3f}, p={p:.4f}')")
            elif m == "oneway_anova":
                lines.append(
                    f"groups = [g['{dv}'].drop_nulls().to_numpy() for _, g in df.group_by('{iv}')]"
                )
                lines.append("f, p = stats.f_oneway(*groups)")
                lines.append("print(f'F={f:.3f}, p={p:.4f}')")
            elif m == "chi_square":
                lines.append(
                    f"ct = df.group_by(['{iv}','{dv}']).len().pivot(values='len', index='{iv}', columns='{dv}').fill_null(0)"
                )
                lines.append("chi2, p, dof, _ = stats.chi2_contingency(ct.to_numpy())")
                lines.append("print(f'chi2={chi2:.3f}, df={dof}, p={p:.4f}')")
            elif m == "linear_regression":
                lines.append(f"X = sm.add_constant(df.select('{iv}').to_numpy())")
                lines.append(f"y = df['{dv}'].to_numpy()")
                lines.append("model = sm.OLS(y, X).fit()")
                lines.append("print(model.summary())")
            elif m in ("descriptive_statistics", "descriptives"):
                lines.append(f"col = df['{dv}'].drop_nulls()")
                lines.append("print(f'M={col.mean():.2f}, SD={col.std():.2f}')")
            elif m == "frequency_analysis":
                lines.append(f"print(df['{dv}'].value_counts())")
            elif m == "mann_whitney":
                lines.append(f"groups_raw = df['{iv}'].drop_nulls().unique().sort().to_list()")
                lines.append(f"mask = df['{dv}'].is_not_null() & df['{iv}'].is_not_null()")
                lines.append(f"g1 = df.filter(mask & (pl.col('{iv}') == groups_raw[0]))['{dv}'].to_numpy()")
                lines.append(f"g2 = df.filter(mask & (pl.col('{iv}') == groups_raw[1]))['{dv}'].to_numpy()")
                lines.append("u, p = stats.mannwhitneyu(g1, g2, alternative='two-sided')")
                lines.append("print(f'U={u:.1f}, p={p:.4f}')")
            elif m == "kruskal_wallis":
                lines.append(
                    f"groups = [g['{dv}'].drop_nulls().to_numpy() for _, g in df.group_by('{iv}')]"
                )
                lines.append("h, p = stats.kruskal(*groups)")
                lines.append("print(f'H={h:.3f}, p={p:.4f}')")
            elif m == "spearman_correlation":
                lines.append(
                    f"rho, p = stats.spearmanr(df['{dv}'].drop_nulls(), df['{iv}'].drop_nulls())"
                )
                lines.append("print(f'rho={rho:.3f}, p={p:.4f}')")
            else:
                lines.append(f"# {m}: {params}")
            lines.append("")

    return "\n".join(lines)
