"""Python code exporter for reproducibility."""

from __future__ import annotations

from quantrix.dag.graph import AnalysisDAG, NodeKind


def export_python(dag: AnalysisDAG, dataset_name: str = "data") -> str:
    lines = [
        '"""Reproducible analysis script generated by Quantrix."""',
        "",
        "import polars as pl",
        "from scipy import stats",
        "import statsmodels.api as sm",
        "",
        f"# Load data: {dataset_name}",
        f"# df = pl.read_csv('{dataset_name}.csv')",
        "",
    ]

    for node in dag.topological_order():
        if node.kind == NodeKind.IMPORT:
            lines.append(f"# Import: {node.description}")
        elif node.kind == NodeKind.ANALYSIS:
            lines.append(f"# {node.label}")
            params = node.parameters
            dv = params.get("dv", "outcome")
            iv = params.get("iv", "predictor")
            m = node.method

            if m == "independent_ttest":
                lines.append(f"g1 = df.filter(pl.col('{iv}') == 0)['{dv}'].drop_nulls()")
                lines.append(f"g2 = df.filter(pl.col('{iv}') == 1)['{dv}'].drop_nulls()")
                lines.append("t, p = stats.ttest_ind(g1.to_numpy(), g2.to_numpy())")
                lines.append("print(f't={t:.3f}, p={p:.4f}')")
            elif m == "pearson_correlation":
                lines.append(f"r, p = stats.pearsonr(df['{dv}'].drop_nulls(), df['{iv}'].drop_nulls())")
                lines.append("print(f'r={r:.3f}, p={p:.4f}')")
            elif m == "oneway_anova":
                lines.append(f"groups = [g['{dv}'].drop_nulls().to_numpy() for _, g in df.group_by('{iv}')]")
                lines.append("f, p = stats.f_oneway(*groups)")
                lines.append("print(f'F={f:.3f}, p={p:.4f}')")
            elif m == "chi_square":
                lines.append(f"ct = df.group_by(['{iv}','{dv}']).len().pivot(values='len', index='{iv}', columns='{dv}').fill_null(0)")
                lines.append("chi2, p, dof, _ = stats.chi2_contingency(ct.to_numpy())")
                lines.append("print(f'chi2={chi2:.3f}, df={dof}, p={p:.4f}')")
            elif m == "linear_regression":
                lines.append(f"X = sm.add_constant(df.select('{iv}').to_numpy())")
                lines.append(f"y = df['{dv}'].to_numpy()")
                lines.append("model = sm.OLS(y, X).fit()")
                lines.append("print(model.summary())")
            elif m in ("descriptive_statistics", "descriptives"):
                lines.append(f"col = df['{dv}'].drop_nulls()")
                lines.append("print(f'M={col.mean():.2f}, SD={col.std():.2f}')")
            elif m == "frequency_analysis":
                lines.append(f"print(df['{dv}'].value_counts())")
            else:
                lines.append(f"# {m}: {params}")
            lines.append("")

    return "\n".join(lines)
